name: Code check
'on':
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*
    paths:
    - .actions/**
    - .github/workflows/code-checks.yml
    - requirements/**
    - src/**
    - pyproject.toml
    - '!requirements/docs.txt'
    - '!requirements/*/docs.txt'
    - '!*.md'
    - '!**/*.md'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref,
    'refs/heads/release/')) }}
defaults:
  run:
    shell: bash
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10.6
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('requirements/pytorch/base.txt') }}
        restore-keys: pip-
        enableCrossOsArchive: true
    - name: Install dependencies
      run: "pip install mypy==0.982  # TODO: pull this verion deom requirements/test.txt\n\
        pip install torch==1.12 --find-links https://download.pytorch.org/whl/cpu/torch_stable.html\n\
        python ./requirements/pytorch/adjust-versions.py requirements/pytorch/extra.txt\n\
        # todo: adjust requirements for both code-bases\npip install \\\n  -r requirements/fabric/base.txt\
        \ \\\n  -r requirements/pytorch/base.txt \\\n  -r requirements/pytorch/extra.txt\
        \ \\\n  -r requirements/app/base.txt \\\n  -r requirements/app/cloud.txt \\\
        \n  -r requirements/app/ui.txt \\\n  --find-links https://download.pytorch.org/whl/cpu/torch_stable.html\n\
        pip list\n"
    - name: Build package
      run: python setup.py build
    - name: Check typing
      run: 'mkdir .mypy_cache

        mypy

        '
